### ISSUE TITLE
Empty gray areas displaying on map.

### ISSUE THREAD

**Issue by Giggitybyte** [comp500/tinymap#6]
I hope this isn't an intentional feature. It'd look much nicer if the map was consistently surrounded by black.
![chrome_QtBkrlyKpt](https://user-images.githubusercontent.com/19187704/118364487-72ea5080-b54d-11eb-88dd-8ac3b28e19fc.png)

Panning up is nothing but light gray.
![chrome_PkbDlZVDyo](https://user-images.githubusercontent.com/19187704/118364490-75e54100-b54d-11eb-8303-a30aef824abf.png)

**Comment by comp500** [comment]
Hmm yeah, I think the dark grey chunks are initialised but not generated chunks, and there's a ring of half-generated chunks. I'll add a check to only render complete chunks and return 404 / render black otherwise

**Comment by Giggitybyte** [comment]
❤️
